# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import listings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.IntegerField(blank=True, choices=[('1', 'Mikina'), ('2', 'Option 2')], null=True, validators=[listings.validators.validate_category]),
        ),
    ]
