# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20181224_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
