# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-24 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_object_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
