# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import listings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20181224_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.CharField(blank=True, choices=[('Mikina', 'Mikina'), ('Boty', 'Boty'), ('Kalhoty', 'Kalhoty'), ('Triko', 'Triko')], max_length=120, null=True, validators=[listings.validators.validate_category]),
        ),
    ]
