# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-24 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20181224_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='picture',
            new_name='image',
        ),
    ]
