# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20181225_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='image',
            field=models.ImageField(blank=True, default='/images/no_image.png', null=True, upload_to='images'),
        ),
    ]
