# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import listings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20190101_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.CharField(blank=True, choices=[('Mikina', 'Mikina'), ('Boty', 'Boty'), ('Kalhoty', 'Kalhoty'), ('Triko', 'Triko'), ('Bunda', 'Bunda')], max_length=120, null=True, validators=[listings.validators.validate_category]),
        ),
    ]
