# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-18 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import listings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20190105_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='size',
        ),
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.CharField(blank=True, choices=[('Mikiny', 'Mikiny'), ('Boty', 'Boty'), ('Kalhoty', 'Kalhoty'), ('Trika', 'Trika'), ('Košile', 'Košile'), ('Doplňky', 'Doplňky'), ('Bundy', 'Bundy')], max_length=120, null=True, validators=[listings.validators.validate_category]),
        ),
        migrations.AddField(
            model_name='sizes',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='listings.Object'),
        ),
    ]
