# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20190118_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='chain',
        ),
        migrations.AddField(
            model_name='object',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
