# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20190118_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
