# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_object_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.Object')),
            ],
        ),
    ]
