# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-22 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_object_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectimages',
            old_name='image',
            new_name='images',
        ),
    ]
