# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-23 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20190122_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectimages',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Object'),
        ),
    ]
