# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-23 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20190123_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='file',
            field=models.FileField(null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='objectimages',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='listings.Object'),
        ),
    ]
