# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-23 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20190123_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.Object')),
            ],
        ),
        migrations.RemoveField(
            model_name='objectimages',
            name='object',
        ),
        migrations.DeleteModel(
            name='ObjectImages',
        ),
    ]
