# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-23 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20190123_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='file',
        ),
    ]
