# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_remove_object_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
