# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-25 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20190124_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='images',
        ),
    ]
