# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-05 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_auto_20190125_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='time',
            new_name='created',
        ),
    ]
