# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_auto_20190205_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
    ]
