# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-14 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_auto_20190205_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to=listings.models.get_image_filename, verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.Object'),
        ),
        migrations.AlterField(
            model_name='object',
            name='price',
            field=models.CharField(blank=True, default='Dohodou', max_length=120, null=True),
        ),
    ]
