# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-24 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20190214_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('reason', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Reports'),
        ),
    ]
