# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-24 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0029_auto_20190224_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='reports',
        ),
        migrations.AddField(
            model_name='reports',
            name='object',
            field=models.ManyToManyField(blank=True, related_name='ReportedObject', to='listings.Object'),
        ),
        migrations.AddField(
            model_name='reports',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
