# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-24 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_auto_20190224_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='object',
        ),
    ]
