# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-24 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_remove_reports_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportedObject', to='listings.Object'),
        ),
    ]
