# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-24 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_auto_20190224_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
