# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-07 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_reports_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='price',
            field=models.IntegerField(blank=True, default='Dohodou', max_length=120, null=True),
        ),
    ]
