# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-19 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_auto_20190310_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
