# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-19 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_object_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='number',
        ),
    ]
