# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-26 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_remove_object_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='objectkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.Object'),
        ),
    ]
