# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-04 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_reports_objectkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='predani',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.CharField(blank=True, choices=[('Mikiny', 'Mikiny'), ('Boty', 'Boty'), ('Kalhoty', 'Kalhoty'), ('Trika', 'Trika'), ('Košile', 'Košile'), ('Doplňky', 'Doplňky'), ('Bundy', 'Bundy')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
