# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-02 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_auto_20190504_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='predani',
            new_name='predan',
        ),
    ]
