# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-16 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_auto_20190602_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
