# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_auto_20190716_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.CharField(blank=True, choices=[('Mikiny', 'Mikiny'), ('Boty', 'Boty'), ('Kalhoty', 'Kalhoty'), ('Trika', 'Trika'), ('Kosile', 'Košile'), ('Doplnky', 'Doplňky'), ('Bundy', 'Bundy'), ('Plavky', 'Plavky'), ('Spodnipradloponozky', 'Spodní prádlo, ponožky'), ('Sport', 'Sport'), ('Kratasy', 'Kraťasy')], max_length=120, null=True),
        ),
    ]
