# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_auto_20190806_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='condition',
            field=models.CharField(blank=True, choices=[('1/10', '1/10'), ('2/10', '2/10'), ('3/10', '3/10'), ('4/10', '4/10'), ('5/10', '5/10'), ('6/10', '6/10'), ('7/10', '7/10'), ('8/10', '8/10'), ('9/10', '9/10'), ('VNDS (jako nové)', 'VNDS (jako nové)'), ('DS (zbrusu nové)', 'DS (zbrusu nové)')], max_length=120, null=True),
        ),
    ]
