# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190108_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/images/no_image.png', null=True, upload_to='images'),
        ),
    ]
