# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-18 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190112_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='auth.User'),
        ),
    ]
