# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-18 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_char',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=240),
        ),
    ]
