# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-18 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_user_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_char',
            field=models.CharField(default='<django.db.models.fields.related.OneToOneField>', max_length=240),
        ),
    ]
