# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190118_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_char',
            field=models.CharField(max_length=240),
        ),
    ]
