# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-22 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190118_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_char',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
