# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-25 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='slug',
            new_name='username',
        ),
    ]
