# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-05 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20190203_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='auth.User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='auth.User'),
        ),
    ]
