# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_auto_20190310_1150'),
        ('profiles', '0016_auto_20190205_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=30, null=True)),
                ('system_rating', models.CharField(max_length=30, null=True)),
                ('user_rating', models.CharField(max_length=30, null=True)),
                ('buyed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyed', to='listings.Object')),
                ('selled_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selled', to='listings.Object')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
