# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-13 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20190310_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='cash',
        ),
    ]
