# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-13 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_remove_deals_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='buyed_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyed_item', to='listings.Object'),
        ),
        migrations.AlterField(
            model_name='deals',
            name='buyer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deals',
            name='selled_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='selled_item', to='listings.Object'),
        ),
        migrations.AlterField(
            model_name='deals',
            name='seller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deals',
            name='system_rating',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='user_rating',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
