# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-13 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20190313_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='buyed_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyed_item', to='listings.Object'),
        ),
        migrations.AlterField(
            model_name='deals',
            name='selled_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selled_item', to='listings.Object'),
        ),
    ]
