# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20190313_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='system_rating',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='user_rating',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
