# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-14 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20190314_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
