# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-18 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20190314_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deals_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
