# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20190318_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='why_system_rating',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='why_user_rating',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='system_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='user_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deals_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
