# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20190329_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='why_system_rating',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='why_user_rating',
        ),
    ]
