# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_auto_20190329_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='why_system_rating',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='why_user_rating',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
