# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20190329_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='system_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='user_rating',
            field=models.IntegerField(null=True),
        ),
    ]
