# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-04 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_deals_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='selled_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(0), related_name='selled_item', to='listings.Object'),
        ),
    ]
