# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_profile_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
