# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-15 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0036_profile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('reason', models.TextField(blank=True, max_length=300, null=True)),
                ('solved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
