# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-27 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_userreport_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
